---
- name: Deploy timesynd.conf
  become: yes
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Run timedatctl to start ntp client
  become: yes
  command: timedatectl set-ntp true

- name: Restart systemd-timesyncd service
  become: yes
  systemd:
    daemon_reload: yes
    name: systemd-timesyncd
    state: restarted
