---
- name: Update package cache
  apt:
    update_cache: yes

- name: Update installed packages
  apt:
    update_cache: no
    upgrade: dist

- name: Update cleanup
  apt:
    autoremove: yes
    autoclean: yes

- name: Install common packages
  apt:
    update_cache: no
    name: '{{ common_packages }}'
    state: present
    install_recommends: no